name: Build Docker containers

jobs:
  build-docker:
    name: Build Docker containers
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main